name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: github.ref == refs/heads/feature/**" || github.ref == 'refs/heads/development'
      env:
        TEST: "HELOOOOOOOOOOOOOOOO"
    - name: print
      run: |
       echo $TEST
