name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: contains(github.ref, 'development')
    - name: test print  
      run: |
       export TEST="HELLLOOOOOOOOOOOOOOOOOOOOOOO"
       echo $TEST && env | grep -i test
