name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      if: contains(github.ref, 'development') || contains(github.ref, 'feature')
      env:
        TEST: "HELOOOOOOOOOOOOOOOOOOOO"
      run: |
       echo $TEST
    - name: END
      run : echo "WELCOME"
